steps:
  # Docker イメージをビルド
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--platform'
      - 'linux/amd64'
      - '-t'
      - 'asia-northeast1-docker.pkg.dev/englishapp-453214/cloud-run-source-deploy/newsappbackend:$COMMIT_SHA'
      - '-t'
      - 'asia-northeast1-docker.pkg.dev/englishapp-453214/cloud-run-source-deploy/newsappbackend:latest'
      - '.'

  # Artifact Registry にプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'asia-northeast1-docker.pkg.dev/englishapp-453214/cloud-run-source-deploy/newsappbackend'

  # Cloud Run にデプロイ
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'newsappbackend'
      - '--image'
      - 'asia-northeast1-docker.pkg.dev/englishapp-453214/cloud-run-source-deploy/newsappbackend:$COMMIT_SHA'
      - '--region'
      - 'asia-northeast1'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--set-env-vars'
      - 'LANGSMITH_TRACING=true,LANGSMITH_ENDPOINT=https://api.smith.langchain.com,LANGSMITH_PROJECT=agent-book'
      - '--set-secrets'
      - 'OPENAI_API_KEY=openai-api-key:latest,LANGSMITH_API_KEY=langsmith-api-key:latest,TAVILY_API_KEY=tavily-api-key:latest'

options:
  logging: CLOUD_LOGGING_ONLY